# Generated by Django 6.0.1 on 2026-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('aba', models.CharField(default='Sheet1', max_length=100)),
                ('tipo_dashboard', models.CharField(choices=[('cobrancas', 'Cobranças / Vencimentos'), ('financeiro', 'Financeiro'), ('fluxo_caixa', 'Fluxo de Caixa')], default='cobrancas', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setor Planilha',
                'verbose_name_plural': 'Setores Planilha',
                'ordering': ['nome'],
            },
        ),
    ]
