# Generated by Django 6.0.1 on 2026-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sheetsetor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsetor',
            name='tipo_dashboard',
            field=models.CharField(choices=[('cobrancas', 'Cobranças / Vencimentos'), ('advocacia', 'Honorários Advocatícios'), ('financeiro', 'Financeiro'), ('fluxo_caixa', 'Fluxo de Caixa')], default='cobrancas', max_length=20),
        ),
    ]
