# Generated by Django 6.0.1 on 2026-03-12 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='Use {nome}, {condominio}, {valor}, {data_atraso} como variáveis.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
