# Generated by Django 6.0.1 on 2026-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sheetsetor_tipo_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_juridico',
            field=models.BooleanField(default=False),
        ),
    ]
