# Generated by Django 6.0.1 on 2026-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_messagetemplate_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'verbose_name': 'Template de mensagem', 'verbose_name_plural': 'Templates de mensagem'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token de redefinição de senha', 'verbose_name_plural': 'Tokens de redefinição de senha'},
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
