# Generated by Django 6.0.1 on 2026-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sheetsetor_tipo_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsetor',
            name='grupo',
            field=models.CharField(blank=True, default='', help_text='Grupo/categoria para agrupar setores (ex: Financeiro, Jurídico)', max_length=100),
        ),
    ]
