# Generated by Django 6.0.1 on 2026-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_messagetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Template de mensagem', 'verbose_name_plural': 'Templates de mensagem'},
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(verbose_name='Corpo da mensagem'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
