# Generated by Django 6.0.1 on 2026-03-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_grupo_to_sheetsetor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetsetor',
            options={'ordering': ['criado_em'], 'verbose_name': 'Setor Planilha', 'verbose_name_plural': 'Setores Planilha'},
        ),
    ]
