# Generated by Django 6.0.1 on 2026-03-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_juridico'),
        ('core', '0006_alter_sheetsetor_options'),
    ]

    operations = [
    ]
