# Generated by Django 6.0.1 on 2026-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260325_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_financeiro',
            field=models.BooleanField(default=False),
        ),
    ]
