# Generated by Django 6.0.1 on 2026-03-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campanha_mensagemEnviada'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mensagemenviada',
            new_name='core_mensag_telefon_8163be_idx',
            old_name='core_mensa_telefon_idx',
        ),
        migrations.RenameIndex(
            model_name='mensagemenviada',
            new_name='core_mensag_campanh_b7041e_idx',
            old_name='core_mensa_campanha_idx',
        ),
    ]
