# Generated by Django 6.0.1 on 2026-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text='Use {nome}, {unidade}, {condominio}, {valor}, {vencimento}, {data_atraso}, {qtd} como variáveis.'),
        ),
    ]
