# Generated by Django 6.0.1 on 2026-03-26 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_messagetemplate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
