# Generated by Django 6.0.1 on 2026-03-30 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messagetemplate_uuid_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaLocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condominio_id', models.IntegerField()),
                ('condominio_nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_por', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa Local',
                'verbose_name_plural': 'Despesas Locais',
                'ordering': ['-vencimento'],
            },
        ),
    ]
