# Generated by Django 6.0.1 on 2026-03-31 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_despesa_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('cor', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('error', 'Vermelho'), ('warning', 'Laranja'), ('info', 'Ciano')], default='primary', max_length=20)),
                ('criado_por', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa de Agenda',
                'verbose_name_plural': 'Tarefas de Agenda',
                'ordering': ['data', 'hora'],
            },
        ),
    ]
