# Generated by Django 6.0.1 on 2026-03-31 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agendatarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaParaPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_despesa', models.CharField(max_length=64)),
                ('id_parcela', models.CharField(blank=True, max_length=64)),
                ('id_contato', models.CharField(blank=True, max_length=64)),
                ('descricao', models.CharField(max_length=500)),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('condominio_id', models.IntegerField()),
                ('condominio_nome', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('marcado_por', models.CharField(blank=True, max_length=255)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa Para Pagar',
                'verbose_name_plural': 'Despesas Para Pagar',
                'ordering': ['marcado_em'],
            },
        ),
    ]
