# Generated by Django 6.0.1 on 2026-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_despesa_para_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendatarefa',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
