# Generated by Django 6.0.1 on 2026-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_checklist_agendatarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='InadimplenciaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('capturado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot de Inadimplência',
                'verbose_name_plural': 'Snapshots de Inadimplência',
                'ordering': ['ano', 'mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
