# Generated by Django 6.0.1 on 2026-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_inadimplencia_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondominioIdValido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_condominio', models.IntegerField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID de Condomínio Válido',
                'verbose_name_plural': 'IDs de Condomínios Válidos',
                'ordering': ['id_condominio'],
            },
        ),
    ]
