# Generated by Django 6.0.1 on 2026-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_responsavel_peticao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavelpeticao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
