# Generated by Django 6.0.1 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_responsavelpeticao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvogadoPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('aba', models.CharField(blank=True, default='', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advogado Planilha',
                'verbose_name_plural': 'Advogados Planilhas',
                'ordering': ['nome'],
            },
        ),
    ]
