# Generated by Django 6.0.1 on 2026-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_condominio_drive_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiodrivemap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
