services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    working_dir: /app/projeto_disparador
    command: >
      sh -c "python manage.py makemigrations core &&
         python manage.py migrate &&
         python manage.py shell -c \"from core.models import User; User.objects.filter(email='admin@admin.com').exists() or User.objects.create_superuser('admin@admin.com', 'admin123', name='Administrador')\" &&
         gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --worker-class gthread --threads 8 --timeout 600"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - web

volumes:
  postgres_data:
